// https://env.t3.gg/docs/nextjs#create-your-schema
import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';


export const serverEnv = createEnv({
  skipValidation: process.env.SKIP_ENV_VALIDATION === '1',
  server: {
    XAI_API_KEY: z.string().min(1),
    OPENAI_API_KEY: z.string().min(1),
    // ANTHROPIC_API_KEY: z.string().min(1),
    GROQ_API_KEY: z.string().min(1),
    GOOGLE_GENERATIVE_AI_API_KEY: z.string().min(1),
    DAYTONA_API_KEY: z.string().min(1),
    DATABASE_URL: z.string().min(1),
    BETTER_AUTH_SECRET: z.string().min(1),
    GITHUB_CLIENT_ID: z.string().min(1),
    GITHUB_CLIENT_SECRET: z.string().min(1),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    TWITTER_CLIENT_ID: z.string().min(1),
    TWITTER_CLIENT_SECRET: z.string().min(1),
    REDIS_URL: z.string().min(1),
    UPSTASH_REDIS_REST_URL: z.string().min(1),
    UPSTASH_REDIS_REST_TOKEN: z.string().min(1),
    ELEVENLABS_API_KEY: z.string().min(1),
    TAVILY_API_KEY: z.string().min(1),
    EXA_API_KEY: z.string().min(1),
    VALYU_API_KEY: z.string().min(1),
    TMDB_API_KEY: z.string().min(1),
    YT_ENDPOINT: z.string().min(1),
    FIRECRAWL_API_KEY: z.string().min(1),
    NOTTE_API_KEY: z.string().optional(),
    PARALLEL_API_KEY: z.string().min(1),
    OPENWEATHER_API_KEY: z.string().min(1),
    GOOGLE_MAPS_API_KEY: z.string().min(1),
    AMADEUS_API_KEY: z.string().min(1),
    AMADEUS_API_SECRET: z.string().min(1),
    CRON_SECRET: z.string().min(1),
    BLOB_READ_WRITE_TOKEN: z.string().min(1),
    SMITHERY_API_KEY: z.string().min(1),
    COINGECKO_API_KEY: z.string().min(1),
    SUPADATA_API_KEY: z.string().min(1),
    QSTASH_TOKEN: z.string().min(1),
    RESEND_API_KEY: z.string().min(1),
    SUPERMEMORY_API_KEY: z.string().min(1),
    SPOTIFY_CLIENT_ID: z.string().min(1),
    SPOTIFY_CLIENT_SECRET: z.string().min(1),
    MCP_CREDENTIALS_ENCRYPTION_KEY: z.string().min(1),
    MCP_OAUTH_CALLBACK_ORIGIN: z.string().url().optional(),
    ALLOWED_ORIGINS: z.string().optional().default('http://localhost:3000'),
    GITHUB_MCP_CLIENT_ID: z.string().optional(),
    GITHUB_MCP_CLIENT_SECRET: z.string().optional(),
    BOX_MCP_CLIENT_ID: z.string().optional(),
    BOX_MCP_CLIENT_SECRET: z.string().optional(),
    DROPBOX_MCP_CLIENT_ID: z.string().optional(),
    DROPBOX_MCP_CLIENT_SECRET: z.string().optional(),
    SLACK_MCP_CLIENT_ID: z.string().optional(),
    SLACK_MCP_CLIENT_SECRET: z.string().optional(),
    HUBSPOT_MCP_CLIENT_ID: z.string().optional(),
    HUBSPOT_MCP_CLIENT_SECRET: z.string().optional(),
    UPSTASH_BOX_API_KEY: z.string().optional(),
    SUB2API_BASE_URL: z.string().url().optional().default('http://127.0.0.1:18080'),
    SUB2API_ADMIN_API_KEY: z.string().optional(),
    OPENALEX_MAILTO: z.string().email().optional(),
    SEMANTIC_SCHOLAR_API_KEY: z.string().optional(),
    ACADEMIC_SEMANTIC_SCHOLAR: z.enum(['true', 'false']).optional().default('false'),
    ACADEMIC_CROSSREF: z.enum(['true', 'false']).optional().default('true'),
    ACADEMIC_ARXIV: z.enum(['true', 'false']).optional().default('true'),
    ACADEMIC_PUBMED: z.enum(['true', 'false']).optional().default('true'),
    ACADEMIC_DOTAINDEX: z.enum(['true', 'false']).optional().default('false'),
    DOTAINDEX_SCHOLAR_PROXY_URL: z.string().url().optional(),
    DOTAINDEX_CAPABILITY_TOKEN: z.string().optional(),
    ACADEMIC_SCHOLAR_673: z.enum(['true', 'false']).optional().default('false'),
    SCHOLAR_673_JSON_PROXY_URL: z.string().url().optional(),
    R2_ACCOUNT_ID: z.string().optional(),
    R2_ACCESS_KEY_ID: z.string().optional(),
    R2_SECRET_ACCESS_KEY: z.string().optional(),
    R2_BUCKET_NAME: z.string().optional(),
    R2_PUBLIC_URL: z.string().url().optional(),
    MY_IMAGE_SCI_SKILL_DIR: z.string().optional(),
    MY_IMAGE_GEN_ENV_FILE: z.string().optional(),
    TSG_ENGLISH_DATABASE_ENTRY_URL: z.string().url().optional(),
  },
  experimental__runtimeEnv: process.env,
});
